name: sast link frontend

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: build
        run: | 
         export SHELL=$(which bash)
         npm i -g pnpm
         pnpm setup
         pnpm i
         pnpm build

         mkdir /tmp/link && cp -r .next /tmp/ && cd /tmp/link
         cat >package.json <<"EOF"
           {
            "name": "sast-link",
            "version": "0.1.0",
            "private": true,
            "scripts": {
              "start": "next start"
            },
            "dependencies": {
              "next": "13.4.8"
            }
          }
         EOF
         pnpm i

      - name: sync to server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -rv --delete
          path: /tmp/link/
          remote_path: /home/link/${{ secrets.HOST }}/frontend/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: restart pm2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.HOST }}/frontend
            pm2 list | grep -q "link" && pm2 restart "sast-link" || pm2 start pnpm --name "sast-link" -- start
